### ISSUE TITLE
Looking forward to pre-trained models

### ISSUE THREAD

**Issue by blx0102** [mutiann/few-shot-transformer-tts#1]
Congratulations to your excellent work! It will be really helpful in multi language TTS systems.
Looking forward to your pre-trained models, which could save so much time for making up the user model. ^^

**Comment by mudong0419** [comment]
Any update?

**Comment by mutiann** [comment]
@blx0102 @mudong0419 Thanks for your interests! It took me some time to prepare the model trained on these open datasets, but they are now done, and there are a number of updates in the code. Please refer to the current version of the repository.
