### ISSUE TITLE
Optimization of model for inference

### ISSUE THREAD

**Issue by mobilec** [mutiann/few-shot-transformer-tts#10]
I was able to train a model for my endangered language but I was wondering if there was any recommend methods in optimizing the model for faster inference, possibly quantization but i'm not sure how i would do that with this model.

Thanks

**Comment by mutiann** [comment]
Thanks for your interests. I haven't tried any quantization methods but it is possibly that such methods could be effective, e.g. simply following pytorch's guide for it.
