### ISSUE TITLE
If I only adaptation few-shot language, should I download the whole train dataset?

### ISSUE THREAD

**Issue by CindyTing** [mutiann/few-shot-transformer-tts#11]
Thanks for your great work! As the title said, let's say I want to adapt on Greek language. is it ok for me to only download Greek language dataset, and then run the few-shot adaptation part? Looking forward to your reply.

**Comment by mutiann** [comment]
Hi,

It is possible to only use the target language data, but other languages serve as a strong regularizer, so using only a small target dataset would lead to worse results or even training failure. If storage and computational resources are limited for using the full dataset for fine-tuning, I would suggest at least incorporate several major rich-resource languages.
