### ISSUE TITLE
Speaker information

### ISSUE THREAD

**Issue by mudong0419** [mutiann/few-shot-transformer-tts#3]
Thanks for your excellent work. It helps me a lot for code-switched TTS. I'm trying to synthesis ZH-EN code-switched speech, the female voice with speaker of databaker is very good. Is there Chinese male speaker in all speakers? Could you please provide speaker's information such as dataset, language?

**Comment by mutiann** [comment]
As all data used are open, please check each dataset for its details. Links to each dataset is given in the corresponding preprocessing scripts. Unfortunately, all Chinese speakers used for the pretrained model are female, and I didn't find a very good open Chinese male voice. If you have such data, you may fine-tune the model with them. Also, you could have a try with male speakers of other languages.
