### ISSUE TITLE
How to finetune on my data.

### ISSUE THREAD

**Issue by mudong0419** [mutiann/few-shot-transformer-tts#4]
I have downloaded VCTK(English) and ST-CMDS(Chinese) dataset, and want to synthesis Chinese-English code-switched speech. What should I do to finetune base on 1160000 checkpoint? Must I download all the dataset list in readme, and then train with --adapt_languages en-us:zh-cn? Many thanks in advance.

**Comment by mutiann** [comment]
I think it is also OK to train only with your own data if the dataset size is sufficiently large. Just preprocess the dataset similar to the current ones, and use --train_languages=en-us:zh-cn

**Comment by mudong0419** [comment]
OK, I will have a try, Thanks a lot.
