### ISSUE TITLE
Export to onnx

### ISSUE THREAD

**Issue by mudong0419** [mutiann/few-shot-transformer-tts#5]
Thanks for your great work, I have trained a zh-en code-switching model finetuning on checkpoint 1160000. But inference speed is no fast enough. I want to export model to onnx, and speed up with onnx_runtime, so the problem is how to export this model to onnx, any advice please. BTW, it's applied in [Huggingface transformes](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py).

**Comment by mutiann** [comment]
I myself don't have experience in ONNX. Maybe you could have a look at the ONNX tutorial of PyTorch?

**Comment by mutiann** [comment]
Besides, inference will be much faster if you save the intermediate state of previous steps in the decoder and reuse it later, otherwise the time complexity will be O(N^3). This is not implemented yet and contributions are welcomed.

**Comment by mudong0419** [comment]
Thanks a lot.
