### ISSUE TITLE
Few-shot adaptation for the low resource language Cherokee

### ISSUE THREAD

**Issue by michael-conrad** [mutiann/few-shot-transformer-tts#6]
I'm working on trying get speech synthesis working for the Cherokee language.

However, looking at the corpora that was used to train the published weights, the amount of data to download exceeds my Internet's and System's capability.

Would the few-shot adaptation from the published weights work if only provided, say, "en-US" ?

As an aside... how much GPU ram is required, I only have a GTX 3070 available here.

```bash
python -m torch.distributed.launch --nproc_per_node=1 train.py --model-dir=MODEL_DIR --log-dir=LOG_DIR --data-dir=DATA_DIR --training_languages=en-us --adapt_languages=chr-w-mco --ddp=True --hparams="warmup_steps=800000" --restore_from=T3_MODEL_DIR/model.ckpt-700000
```

**Comment by michael-conrad** [comment]
Public Cherokee language audio data is at: https://github.com/CherokeeLanguage/cherokee-audio-data

**Comment by mutiann** [comment]
I haven't tried to adapt a model trained on multiple source languages to a target when co-training only with a single language. As mentioned in the paper, the basic idea is that the more source language used the better results can be achieved; the similarity between the source and the target help, but is not that important. Therefore I guess that your method might work, but the results might not be very good. I suggest that maybe you can use as many languages as you can in the co-training from a T2/T3 model, including some more European languages written in the Latin alphabet. 

The original experiments were done on 4 GPUs, each with 16GB memory. With only 1 GPU you don't need to switch on --ddp, and there are many methods to reduce memory costs like reducing batch size (which may affect the performance) and accumulate the gradients (which costs more training time).
