### ISSUE TITLE
Setup instructions are incomplete: No module named 'hyperparams'

### ISSUE THREAD

**Issue by michael-conrad** [mutiann/few-shot-transformer-tts#7]
I'm trying to do the initial preprocess step, but the run errors out with ```No module named 'hyperparams'```.

```python
python corpora/process_corpus.py 
Traceback (most recent call last):
  File "/opt/data1/muksihs/git/Cherokee-TTS-fst/corpora/process_corpus.py", line 3, in <module>
    from hyperparams import hparams as hp
ModuleNotFoundError: No module named 'hyperparams'
```

I tried doing pip -e for the root directory of the project, but that complains: ```ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode:```

Assistance would be appreciated.

**Comment by mutiann** [comment]
It is actually hyperparams.py in the code. To allow python to find this, you need to add the absolute path of the repository to the environment variable PYTHONPATH.
