### ISSUE TITLE
The scottish_english_male archive for Google appears to have changed the extension for line_index.tsv to line_index.csv

### ISSUE THREAD

**Issue by michael-conrad** [mutiann/few-shot-transformer-tts#8]
Traceback (most recent call last):
  File "google.py", line 135, in <module>
    merge()
  File "google.py", line 51, in merge
    lines = open(os.path.join(f, "line_index.tsv"), "r", encoding='utf-8').read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: '../data/datasets/google/scottish_english_male/line_index.tsv'

**Comment by mutiann** [comment]
Since the Scottish data is not part of the datasets I originally used, you may need to change the script to adapt to it. For this one, modify the process function in google.py.
